# Generated by Django 3.0.6 on 2024-10-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20241024_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_login_role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
