# Generated by Django 3.0.6 on 2024-10-23 04:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerApplicationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('application_status', models.CharField(blank=True, default='pending', max_length=30, null=True)),
                ('is_rejected', models.BooleanField(default=False)),
                ('reason', models.TextField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'seller_application_details',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('bussiness_name', models.CharField(blank=True, max_length=150, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.PositiveIntegerField(blank=True, unique=True)),
                ('gst_number', models.CharField(max_length=20)),
                ('pan_number', models.CharField(max_length=15, unique=True)),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc_number', models.CharField(max_length=15)),
                ('return_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('iu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SellerProfile_iu_id', to='adminapp.IUMaster')),
                ('seller_application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_approval', to='seller.SellerApplicationDetails')),
            ],
            options={
                'db_table': 'seller_profile',
                'ordering': ['created_at'],
            },
        ),
    ]
