# Generated by Django 3.0.6 on 2024-10-23 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('seller', '0001_initial'),
        ('adminapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerapplicationdetails',
            name='iu_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SellerApplicationDetails_iu_id', to='adminapp.IUMaster'),
        ),
        migrations.AddField(
            model_name='sellerapplicationdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
