# Generated by Django 3.0.6 on 2024-10-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_auto_20241023_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
