# Generated by Django 3.0.6 on 2024-11-26 12:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_auto_20241025_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='updated_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='return_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
