# Generated by Django 3.0.6 on 2024-11-27 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0004_auto_20241126_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellerprofile',
            old_name='updated_data',
            new_name='updated_profile',
        ),
    ]
