# Generated by Django 3.0.6 on 2024-11-14 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
