# Generated by Django 3.0.6 on 2024-11-19 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0002_notification_email_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmaster',
            name='sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='web',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sms_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='web_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
