# Generated by Django 3.0.6 on 2024-10-23 04:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IUMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('domain', models.CharField(max_length=50)),
                ('contact_mobile_no', models.CharField(max_length=15)),
                ('logo', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'iu_master',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IUJsonMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('channel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('document_type', models.CharField(blank=True, max_length=50, null=True)),
                ('document_name', models.CharField(blank=True, max_length=30, null=True)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('version', models.CharField(default=1, max_length=5)),
                ('iu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iu_jsonmaster', to='adminapp.IUMaster')),
            ],
            options={
                'db_table': 'iujsonmaster',
                'ordering': ['created_at'],
            },
        ),
    ]
