# Generated by Django 3.0.6 on 2024-10-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iumaster',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
