# Generated by Django 3.0.6 on 2024-10-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20241022_0626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iumaster',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelTable(
            name='iumaster',
            table='iu_master',
        ),
    ]
