# Generated by Django 3.0.6 on 2024-10-29 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20241023_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProductVariation_variation', to='order.VariantOption'),
        ),
    ]
