# Generated by Django 3.0.6 on 2024-10-29 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20241029_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmaster',
            old_name='subcategroy',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='variantmaster',
            old_name='categroy',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='can_be_deleted',
        ),
        migrations.RemoveField(
            model_name='variantmaster',
            name='can_be_deleted',
        ),
        migrations.AlterModelTable(
            name='variantmaster',
            table='variant_master',
        ),
        migrations.AlterModelTable(
            name='variantoption',
            table='variant_option',
        ),
    ]
