# Generated by Django 3.0.6 on 2024-11-05 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0001_initial'),
        ('order', '0004_auto_20241029_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productmaster',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True),
        ),
        migrations.CreateModel(
            name='InvoiceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('invoice_number', models.IntegerField(blank=True, unique=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('total_discount_persentage', models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True)),
                ('total_discount_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('overall_total', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('iu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.IUMaster')),
                ('order_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_invoice_model', to='order.OrderDetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invoice_model', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoice_model',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_invoiceitems', to='order.InvoiceModel')),
                ('iu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.IUMaster')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_product', to='order.ProductVariation')),
            ],
            options={
                'db_table': 'invoice_items',
                'ordering': ['created_at'],
            },
        ),
    ]
