# Generated by Django 3.0.6 on 2024-11-06 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20241105_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicemodel',
            old_name='total_discount_persentage',
            new_name='total_discount_percentage',
        ),
    ]
