# Generated by Django 3.0.6 on 2024-11-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20241106_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitems',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
