# Generated by Django 3.0.6 on 2024-11-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20241106_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaster',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='productmaster',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=3, null=True),
        ),
    ]
