# Generated by Django 3.0.6 on 2024-11-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20241107_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
