# Generated by Django 3.0.6 on 2024-11-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20241107_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='total_discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
