# Generated by Django 3.0.6 on 2024-11-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20241107_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitems',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicemodel',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
