# Generated by Django 3.0.6 on 2024-11-08 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20241107_1618'),
        ('order', '0009_auto_20241108_1156'),
    ]

    operations = [
    ]
