# Generated by Django 3.0.6 on 2024-11-13 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_auto_20241112_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdetails',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbackdetails_product', to='order.ProductVariation'),
        ),
    ]
