# Generated by Django 3.0.6 on 2024-11-14 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20241113_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmaster',
            old_name='image',
            new_name='images',
        ),
    ]
