# Generated by Django 3.0.6 on 2024-11-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_auto_20241114_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorymaster',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, related_name='product_subcategory', to='order.ProductCategoryMaster'),
        ),
    ]
