# Generated by Django 3.0.6 on 2024-11-20 11:21

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('order', '0016_auto_20241119_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentdetails',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='feedbackdetails',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='feedbackdetails',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='feedbackdetails',
            name='dislikes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='feedbackdetails',
            name='likes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='due',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='order',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='paymentdetails',
            table='payment_details',
        ),
        migrations.CreateModel(
            name='PaymentReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_refernce_payment_detail', to='order.PaymentDetails')),
                ('payment_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_reference_payment_type', to='order.PaymentTypeMaster')),
            ],
            options={
                'db_table': 'payment_refernce',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderTypeMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('iu_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordertypemaster_iuid', to='adminapp.IUMaster')),
            ],
            options={
                'db_table': 'order_type',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='ordertype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_details_order_type', to='order.OrderTypeMaster'),
        ),
    ]
