# Generated by Django 3.0.6 on 2024-11-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20241120_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategorymaster',
            name='can_be_editable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productcategorymaster',
            name='can_be_deleted',
            field=models.BooleanField(default=True),
        ),
    ]
