# Generated by Django 3.0.6 on 2024-11-21 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0018_auto_20241120_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackdetails',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='feedbackdetails',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='feedbackdetails_dislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='feedbackdetails',
            name='likes',
        ),
        migrations.AddField(
            model_name='feedbackdetails',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='feedbackdetails_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
