# Generated by Django 3.0.6 on 2024-11-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_auto_20241121_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='item_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='consumable_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
