# Generated by Django 3.0.6 on 2024-11-25 10:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20241122_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdetails',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
