# Generated by Django 3.0.6 on 2024-11-26 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0021_auto_20241125_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderItems_seller', to=settings.AUTH_USER_MODEL),
        ),
    ]
