# Generated by Django 3.0.6 on 2024-12-02 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_auto_20241126_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackdetails',
            name='product',
        ),
        migrations.AddField(
            model_name='feedbackdetails',
            name='product_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_feedback_details', to='order.ProductMaster'),
        ),
        migrations.AddField(
            model_name='feedbackdetails',
            name='product_varient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productvariant_feedback', to='order.ProductVariation'),
        ),
    ]
