# Generated by Django 3.0.6 on 2024-12-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20241202_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='is_removed',
        ),
        migrations.RemoveField(
            model_name='variantmaster',
            name='category',
        ),
        migrations.RemoveField(
            model_name='variantoption',
            name='image',
        ),
    ]
